// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * API 错误结构，包含错误码、脱敏消息和内部详情。
 *
 * - `code`：错误码，前端据此进行逻辑分支。
 * - `message`：用户可读的脱敏描述，不含任何敏感信息。
 * - `details`：内部详细错误上下文（如堆栈、路径哈希等），仅用于日志记录，
 *   通过 `#[serde(skip)]` 不序列化到前端响应，防止信息泄露。
 */
export type ApiError = { 
/**
 * 错误码
 */
code: ErrorCode, 
/**
 * 用户可读的脱敏消息
 */
message: string, };
