// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 权限令牌生成结果
 */
export type AuthTokenResult = { ok: boolean, token: string | null, detail: string, };
