// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 暴力拦截检查结果（序列化给前端）
 */
export type BruteForceCheckResponse = { "kind": "Allow" } | { "kind": "Locked", remaining_secs: number, } | { "kind": "PurgeRequired" };
