// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 暴力拦截状态快照
 */
export type BruteForceStatus = { consecutive_failures: number, total_failures: number, remaining_lock_secs: number, purge_required: boolean, };
