// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 第 7.2/7.3/7.5 项：剪贴板清空结果（结构化返回）
 *
 * 替代恒成功返回，提供类型安全的剪贴板操作结果。
 * error_code 供前端差异化处理（CLIPBOARD_LOCKED / RATE_LIMITED / CLIPBOARD_MONITOR_FAILED）。
 */
export type ClipboardResult = { 
/**
 * 操作是否成功（true=剪贴板已安全擦除）
 */
ok: boolean, 
/**
 * 用户可读描述（不含敏感信息）
 */
detail: string, 
/**
 * 第 7.2/7.3/7.5 项：标准化错误码
 *
 * 取值：
 *   - CLIPBOARD_LOCKED：剪贴板被占用，重试后仍失败
 *   - RATE_LIMITED：频率超限（>10次/分钟）
 *   - CLIPBOARD_MONITOR_FAILED：监听启动失败
 *   - TEMPORARY_FAILURE：临时性故障
 *   - INTERNAL：内部错误
 */
error_code?: string, };
