// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 设备绑定状态枚举
 *
 * 替代字符串状态，提供类型安全的设备绑定结果。
 */
export type DeviceBindingStatus = "match" | "mismatch" | "unbound" | "partial_match" | "error";
