// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceBindingStatus } from "./DeviceBindingStatus";

/**
 * 设备绑定校验结果（结构化返回）
 *
 * 替代魔术字符串，提供类型安全的设备绑定结果。
 * status 为状态枚举，detail 为用户可读描述，error_code 供前端差异化处理。
 */
export type DeviceBindingResult = { 
/**
 * 绑定状态枚举（match/mismatch/unbound/partial_match/error）
 */
status: DeviceBindingStatus, 
/**
 * 用户可读描述（不含敏感信息）
 */
detail: string, 
/**
 * 错误码（status=error 时有值）
 */
error_code?: string, 
/**
 * 匹配度百分比（0-100，status=match/partial_match 时有值）
 */
match_score?: number, };
