// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 诊断信息（删除 worker_path/dll_path/cwd，改存在性/哈希标识）
 *
 * 变更清单：
 *   - 删除 worker_path: String（不泄露路径）
 *   - 删除 dll_path: String（不泄露路径）
 *   - 删除 cwd: String（不泄露工作目录）
 *   - 新增 worker_exists: bool（保留，原已有）
 *   - 新增 dll_hash: String（DLL SHA-256 哈希前 16 字符，用于完整性诊断）
 *   - 新增 worker_pid: Option<u32>（worker 进程 PID，运行中时有值）
 */
export type DiagInfo = { 
/**
 * worker 可执行文件是否存在
 */
worker_exists: boolean, 
/**
 * DLL 文件是否存在
 */
dll_exists: boolean, 
/**
 * worker 是否运行中
 */
worker_running: boolean, 
/**
 * DLL SHA-256 哈希前 16 字符（完整性诊断用）
 *
 * 从 build.rs 生成的 dll_hash.rs 读取，用于诊断 DLL 完整性。
 * 空字符串表示 DLL 未找到或哈希未生成（开发模式）。
 */
dll_hash: string, 
/**
 * worker 进程 PID（运行中时有值）
 */
worker_pid: number | null, };
