// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";
import type { VerthysRecordEntry } from "./VerthysRecordEntry";

/**
 * 枚举记录流式分页批次（Tauri Channel 推送载荷）
 *
 * verthys_enumerate_records_stream 命令循环调用 worker enumerate_records，
 * 每批返回通过 on_batch Channel 推送到前端。前端收到一批即渲染一批，
 * 用户感知为渐进式加载而非"瞬间冻结后爆发"，单批处理时间 < 5ms。
 *
 * 增加 error: Option<ApiError> 字段
 * 批次失败时通过此字段返回错误信息，前端据此决定是否停止循环。
 */
export type EnumerateBatch = { 
/**
 * 本批记录列表（id/type/name/dataB64）
 */
records: Array<VerthysRecordEntry>, 
/**
 * 本批最后一条记录的 ID（前端据此发起下一批，0 表示无记录）
 */
last_id: number, 
/**
 * 本批记录数
 */
count: number, 
/**
 * 是否已遍历完毕（true 时前端停止循环）
 */
exhausted: boolean, 
/**
 * 累计已推送记录数（用于前端进度展示）
 */
total_pushed: number, 
/**
 * 批次错误信息（失败时前端据此停止循环）
 */
error?: ApiError, };
