// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 加密库初始化状态枚举（第 8.5 项）
 *
 * 替代字符串状态（"none"/"ready"/"broken"），提供类型安全。
 * 前端通过枚举变体进行差异化处理。
 */
export type InitStatus = "none" | "initializing" | "ready" | "broken" | "maintenance";
