// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitStatus } from "./InitStatus";

/**
 * 初始化状态查询结果（第 8.5 项：使用 InitStatus 枚举）
 *
 * 阶段 1 保留 status: String 字段（向后兼容），
 * 新增 status_enum: Option<InitStatus> 字段供前端渐进迁移。
 * 阶段 8 移除 status 字段，统一使用 status_enum。
 */
export type InitStatusResult = { 
/**
 * 状态字符串（向后兼容，阶段 8 移除）
 *
 * 取值："none" | "ready" | "broken" | "initializing" | "maintenance"
 */
status: string, 
/**
 * 第 8.5 项：状态枚举（类型安全，阶段 8 替代 status 字段）
 */
status_enum?: InitStatus, 
/**
 * 加密库路径（ready 时有值，脱敏后返回）
 */
verthys_path: string | null, 
/**
 * 状态文件描述
 */
detail: string, };
