// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 路径预检结果（第 8.3 项：删除 dir 字段；第 3.4 项：错误码脱敏）
 *
 * 第 8.3 项：删除 dir 字段，前端不再接收路径信息。
 * 第 3.4 项：失败时仅返回标准化错误码 + 无路径提示，不泄露路径。
 *   错误码取值：INVALID_PATH / PERMISSION_DENIED / DISK_SPACE_INSUFFICIENT
 *   / DISK_SPACE_UNKNOWN / TEMPORARY_FAILURE
 * 详细路径与错误原因仅写入后端日志（经 sanitize_path 脱敏）。
 */
export type PreflightResult = { ok: boolean, error: string | null, 
/**
 * 第 3.4 项：标准化错误码（前端据此差异化处理，不含路径信息）
 */
error_code?: string, 
/**
 * 第 8.3 项：删除 dir 字段（不透传路径到前端）
 */
is_system_protected: boolean, file_exists: boolean, 
/**
 * 磁盘剩余空间（MB）
 */
disk_space_mb: number, 
/**
 * 是否自动创建了目录
 */
dir_created: boolean, };
