// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PresetFeatures = { anti_debug: boolean, anti_inject: boolean, integrity_check: boolean, memory_guard: boolean, key_separation: boolean, emergency_response: boolean, session_lock_on_idle: boolean, shadow_sleep: boolean, module_patrol: boolean, clip_clear_on_lock: boolean, usb_clone_detect: boolean, trace_cleanup: boolean, };
