// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetFeatures } from "./PresetFeatures";

/**
 * 三档安全预设配置（前端展示用）
 */
export type PresetConfig = { 
/**
 * 预设名称：BALANCED / SECURE / PERFORMANCE
 */
name: string, 
/**
 * 预设代号：0=BALANCED, 1=SECURE, 2=PERFORMANCE
 */
code: number, 
/**
 * 各安全特性开关
 */
features: PresetFeatures, };
