// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 防截屏保护状态快照
 *
 * 前端据此决定按钮状态、是否需要接管会话与是否给出恢复入口；
 * 状态与槽位是两处字段的组合，由后端一次锁内读取给出。
 */
export type PrivacyStatusResult = { 
/**
 * 状态机：disabled / enabled / transitioning / quarantined
 */
state: string, 
/**
 * 凭证槽位：empty / pending_adoption / active
 */
slot: string, 
/**
 * 受保护窗口数量
 */
protected_count: number, 
/**
 * 隔离原因（仅 quarantined 时存在）
 *
 * 取值：rollback_failed / stuck_in_transition /
 * token_invariant_violation / reconcile_failed
 */
quarantined_reason?: string, };
