// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 隐私模式设置结果（结构化返回）
 *
 * 替代恒成功返回，提供类型安全的隐私模式切换结果。
 * partial_protection=true 表示防截屏已启用但剪贴板监听启动失败（部分保护）。
 */
export type PrivacyModeResult = { 
/**
 * 操作是否成功（true=隐私模式已按预期切换）
 */
ok: boolean, 
/**
 * 隐私模式当前状态（true=已启用，false=已关闭）
 */
enabled: boolean, 
/**
 * 是否处于部分保护状态
 *
 * true 表示防截屏已启用但剪贴板监听启动失败，前端应警告用户。
 */
partial_protection: boolean, 
/**
 * 用户可读描述（不含敏感信息）
 */
detail: string, 
/**
 * 标准化错误码
 *
 * 取值：
 *   - CLIPBOARD_MONITOR_FAILED：剪贴板监听启动失败（partial_protection=true）
 *   - RATE_LIMITED：频率超限（>10次/分钟）
 *   - PERMISSION_DENIED：关闭隐私模式缺少授权令牌
 *   - TEMPORARY_FAILURE：临时性故障
 *   - INTERNAL：内部错误
 */
error_code?: string, 
/**
 * 会话令牌（仅 enabled=true 时返回）
 *
 * 启用隐私模式时生成的随机令牌，前端需存储并在关闭时作为 auth_token 传入。
 * 关闭操作要求此令牌匹配，防止恶意脚本无凭据关闭保护。
 */
session_token?: string, };
