// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 防截屏保护设置结果（结构化返回）
 *
 * 窗口捕获排除为整体成功或整体失败，不存在部分保护：
 * partial_protection 字段保留以维持结构稳定，其值恒为假。
 */
export type PrivacyModeResult = { 
/**
 * 操作是否成功（true=保护已按预期切换）
 */
ok: boolean, 
/**
 * 保护当前状态（true=已启用，false=已关闭）
 */
enabled: boolean, 
/**
 * 恒为假：保护不存在"部分成功"，保留字段仅为契约稳定
 */
partial_protection: boolean, 
/**
 * 用户可读描述（不含敏感信息）
 */
detail: string, 
/**
 * 标准化错误码
 *
 * 取值：
 *   - PRIVACY_BUSY：已有过渡进行中
 *   - PRIVACY_QUARANTINED：处于隔离状态，需先对账修复
 *   - PRIVACY_NO_TARGET_WINDOW：未找到可保护窗口
 *   - PRIVACY_VERIFY_MISMATCH：设置后回读值不符
 *   - PRIVACY_ROLLED_BACK：失败并已还原，可重试
 *   - PRIVACY_TOKEN_MISSING：关闭未提供凭证
 *   - PRIVACY_TOKEN_INVALID：凭证不匹配
 *   - PRIVACY_LEASE_HELD：已有未决关闭操作
 *   - PRIVACY_LEASE_EXPIRED：凭证世代已变更
 *   - PRIVACY_NOT_RESTORED / PRIVACY_ALREADY_ADOPTED：采纳状态不符
 *   - PRIVACY_TOKEN_INVARIANT_VIOLATION：槽位不变式被破坏
 *   - PRIVACY_TRANSITION_SUPERSEDED：过渡被新的状态变更取代
 *   - RATE_LIMITED：频率超限
 */
error_code?: string, 
/**
 * 会话令牌（仅开启成功时返回一次）
 *
 * 关闭保护需作为 auth_token 传入；成功后即失效、失败后仍可重试，
 * 不可重复使用，也不存在无授权的重新签发入口。
 */
session_token?: string, };
