// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 记录 ID newtype（第 8.7 项）
 *
 * 替代裸 u64，提供类型安全防止与其他 u64 字段混淆。
 */
export type RecordId = number;
