// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 零化擦除的安全字符串
 *
 * 包装 `Zeroizing<String>`：
 *   - 序列化/反序列化透明（作为普通 JSON 字符串），前端契约无感
 *   - `Deref<Target=str>` 兼容现有 `as_str()` / `len()` / `is_empty()` / `as_bytes()` / `as_ptr()` 调用
 *   - Drop 时自动 zeroize 堆内存（String::zeroize 先 volatile 写零再 clear，无 UB）
 *   - 实现 `Zeroize` trait 供泛型 `ScanRecord: Zeroize` 约束使用
 *
 * 用于 VerthysRecordEntry.name / data 与 VerthysSummaryEntry.name / merkle_leaf 字段，
 * 替代裸 String，消除 secure_zero_records 中 ptr::write_bytes 对 String 的 UB 覆写。
 *
 * 注意：不 derive Hash（Zeroizing<String> 未实现 Hash）。
 */
export type SecuredString = string;
