// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 敏感操作结构化结果
 */
export type SecurityResult = { 
/**
 * 操作是否成功
 */
ok: boolean, 
/**
 * 用户可读描述
 */
detail: string, 
/**
 * 错误码（PERMISSION_DENIED / INVALID_TOKEN / INVALID_PATH / RATE_LIMITED / INTERNAL）
 */
error_code?: string, };
