// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 影子休眠状态（第 13.2.8 项：返回真实 txid）
 */
export type ShadowSleepStatus = { in_shadow_sleep: boolean, txid: number, };
