// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模块巡检结果中的未知模块
 */
export type UnknownModuleInfo = { name: string, path: string, reason: string, };
