// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecuredString } from "./SecuredString";

/**
 * 摘要扫描返回的单条记录（轻量元数据，不含数据块）
 *
 * 与 VerthysRecordEntry 的区别：
 *   - 无 data 字段（不解密数据块，解锁后 1-2 秒内完成列表渲染）
 *   - 新增 data_size / physical_offset / merkle_leaf（供按需加载定位 + 完整性校验）
 *   - 新增 created_time（创建时间戳，解锁后立即展示在列表中）
 *
 * merkle_leaf 以 base64 传输（32 字节 → 44 字符），前端用于全盘完整性巡检。
 *
 * name / merkle_leaf 改为 SecuredString（Zeroizing<String>）：
 *   Drop 时自动零化堆内存，消除 secure_zero_summary_records 中 ptr::write_bytes UB。
 */
export type VerthysSummaryEntry = { id: number, rtype: number, 
/**
 * 记录名称（SecuredString，Drop 时零化擦除）
 */
name: SecuredString, 
/**
 * 原始数据大小（字节，用于显示"大小"列）
 */
data_size: number, 
/**
 * 物理槽位偏移（按需加载时直接定位磁盘位置，跳过 B+ 树查找）
 */
physical_offset: number, 
/**
 * Merkle 叶子哈希 base64（SecuredString，完整性校验码，Drop 时零化）
 */
merkle_leaf: SecuredString, 
/**
 * 创建时间戳（Unix 秒，列表展示用）
 */
created_time: number, };
